// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

// Locations
export const FETCH_PROVINCES_REQUEST = 'FETCH_PROVINCES_REQUEST';
export const FETCH_PROVINCES_SUCCESS = 'FETCH_PROVINCES_SUCCESS';
export const FETCH_PROVINCES_FAILURE = 'FETCH_PROVINCES_FAILURE';
export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

// Listings
export const CREATE_LISTING_REQUEST = 'CREATE_LISTING_REQUEST';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_ERROR = 'CREATE_LISTING_ERROR';
export const CLEAR_LISTING_STATE = 'CLEAR_LISTING_STATE';
export const FETCH_LISTINGS_REQUEST = 'FETCH_LISTINGS_REQUEST';
export const FETCH_LISTINGS_SUCCESS = 'FETCH_LISTINGS_SUCCESS';
export const FETCH_LISTINGS_ERROR = 'FETCH_LISTINGS_ERROR';
export const FETCH_LISTINGS_BY_PROVINCE_REQUEST = 'FETCH_LISTINGS_BY_PROVINCE_REQUEST';
export const FETCH_LISTINGS_BY_PROVINCE_SUCCESS = 'FETCH_LISTINGS_BY_PROVINCE_SUCCESS';
export const FETCH_LISTINGS_BY_PROVINCE_ERROR = 'FETCH_LISTINGS_BY_PROVINCE_ERROR';
export const FETCH_LISTING_DETAILS_REQUEST = "FETCH_LISTING_DETAILS_REQUEST";
export const FETCH_LISTING_DETAILS_SUCCESS = "FETCH_LISTING_DETAILS_SUCCESS";
export const FETCH_LISTING_DETAILS_ERROR = "FETCH_LISTING_DETAILS_ERROR";
export const REPORT_LISTING_REQUEST = "REPORT_LISTING_REQUEST";
export const REPORT_LISTING_SUCCESS = "REPORT_LISTING_SUCCESS";
export const REPORT_LISTING_ERROR = "REPORT_LISTING_ERROR";

// Common
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

// Private
export const FETCH_USER_LISTINGS_REQUEST = "FETCH_USER_LISTINGS_REQUEST";
export const FETCH_USER_LISTINGS_SUCCESS = "FETCH_USER_LISTINGS_SUCCESS";
export const FETCH_USER_LISTINGS_ERROR = "FETCH_USER_LISTINGS_ERROR";